#baseURL = "http://localhost:1313/"
baseURL = "https://butirandebu.my.id/"
languageCode = "en-us"
paginate = 6
summarylength = 10
title = "Butiran Debu | Personal Blog"
theme = "blogge-hugo-theme"
#themeDir = "themes/blogge-hugo-theme"

[menu]
  [[menu.main]]
    name = "Home"
    url= ""
    weight= 1
  [[menu.main]]
    name = "About"
    url= "about"
    weight= 2
  [[menu.main]]
    name = "Contact"
    url= "contact"
    weight= 3

[params]
  summarylength = 80
  logo = "images/logo.svg"
  author = "Butiran Debu"
  authorThumb = "images/author.png"
  thumbnail = "images/author.png"
  authorAddress = "Lorem 142 Str., 2352, Ipsum, State, USA"
  authorPhone = "+33-257634 534"
  instaUsername = "#"
  facebookUsername = "#"
  twitterUsername = "#"
  linkedinUsername = "#"
  blogTitle = "Articles"
  blogSubTitle = "View the latest Articles on Butiran Debu"
  trendingBlogIcon = "images/blog/icon.svg"
  # Replace the third party URL/API with yours
  # We're using formspree.io for form handling, paste your formspree url below
  fabformURL  = "9AJk8ro"
  googleMapAPI = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"

[taxonomies]
  tag = "tags"
